/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck

/** Import of types - No need to touch */
import type { Site } from '$lib/types/site'; 
import type { Giscus } from '$lib/types/giscus';
import type { DD } from '$lib/types/dd';

/** Autogenerated Images - No need to touch? */
import Avatar_128 from '$assets/avatar.png?w=128&h=128&format=avif;wepb';
import Avatar_48_PNG from '$assets/avatar.png?w=48&h=48';
import Avatar_96_PNG from '$assets/avatar.png?w=96&h=96';
import Avatar_192_PNG from '$assets/avatar.png?w=192&h=192';
import Avatar_512_PNG from '$assets/avatar.png?w=512&h=512';

/** Avatar image path - Need to overwrite with own image in folder user/assets/ */ 
import Avatar from '$assets/avatar.png';

/** Default post image path - Need to overwrite with own image in folder user/assets/ */
import DefaultOGCard_512_512 from '$assets/default_og_card.jpg?w=512&h=512&format=webp';

/** Basic site details - Need to change with user custom
 *  could this be set with CLI or GUI? 
 * */
export const siteConfig: Site.Config = {
  /**Site domain used in:
   * Head as rel=canonical https://www.seoinhouse.es/que-es-el-relcanonical-y-para-que-sirve/ 
   * Meta tag & open graph https://ogp.me/
   * In the user widget as hidden u-url u-uid from microformats2??
   */
  url: 'https://str3dlok.com/', 
  
  /** Site title used in homepage:
   *  Head title
   *  Meta tag 
   *  Open Graph tag og:site_name
   *  Open Graph tag og:title
   *  In the top navigation as text-logo
   *  In posts it's get overwrittten with the frontmatter
  */
  title: 'Str3Dlok',

  /** Is this not used anywhere???
   *  used internally??
   */
  subtitle: 'qwerty',

  /** Site description used in:
   * Only the head tag and opengraph tag description in home page.
   * Only needed in home? https://moz.com/learn/seo/meta-description
   * In posts it's get overwrittten with the frontmatter
   * It the text shown in search engines as the content of the site
   */
  description: 'Str3Dlok 3D Blender Unreal',

  /** Site language used in:
   *  Main html tag as attribute
   *  Tag og:locale - open graph https://ogp.me/
   * 
  */
  lang: 'es',

  /** Site timezone 
   *  used internally??
  */
  timeZone: 'Europe/Madrid',

  /** Site copyright initial year used in:
   * footer, it takes the year of this field and add current year
   */
  since: 2019,

  /** Author custom data in home:
   *  meta tag name=author
   * 
   */
  author: {
    name: 'findeme',
    status: '😘',
    statusTip: '<a href="https://github.com/kwchang0831/svelte-QWER" style="color:#0F0" onMouseOver="this.style.color=\'#0FF\'" onMouseOut="this.style.color=\'#0F0\'" >QWER</a> is Awesome !',
    avatar: Avatar,
    avatar_128: Avatar_128,
    avatar_48_png: Avatar_48_PNG,
    avatar_96_png: Avatar_96_PNG,
    avatar_192_png: Avatar_192_PNG,
    avatar_512_png: Avatar_512_PNG,
    website: 'https://github.com/kwchang0831/svelte-QWER',
    github: 'https://github.com/kwchang0831',
    email: 'str3dlok@gmail.com',
    bio: `lorem ipsum! <br/> dolor sit amet!`,
  },
  og_card: DefaultOGCard_512_512,
};

/** */
export const headConfig: Site.Head = {
  // Used for IndieWeb
  me: ['https://github.com/kwchang0831'],
  custom: ({ dev }) =>
    dev
      ? [
          // For Development Enviroment
        ]
      : [
          // For Production Enviroment
          '<link rel="preconnect" href="https://plausible.kwchang0831.dev" />',
          '<script defer data-domain="svelte-qwer.vercel.app" src="https://plausible.kwchang0831.dev/js/plausible.js"></script>',
        ],
};

/** */
export const dateConfig: Site.DateConfig = {
  toPublishedString: {
    locales: 'en-US',
    options: {
      year: 'numeric',
      weekday: 'short',
      month: 'short',
      day: 'numeric',
      timeZone: `${siteConfig.timeZone}`,
    },
  },
  toUpdatedString: {
    locales: 'en-US',
    options: {
      year: 'numeric',
      weekday: 'short',
      month: 'short',
      day: 'numeric',
      timeZone: `${siteConfig.timeZone}`,
    },
  },
};

/** Giscus is a comments system based on Github Discussions */
export const giscusConfig: Giscus.Config = {
  // src: 'https://unpkg.com/giscus?svelte',
  enable: true,
  id: 'giscus-comment',
  repo: 'kwchang0831/svelte-QWER',
  repoId: 'R_kgDOHiLP-g',
  category: 'Comments',
  categoryId: 'DIC_kwDOHiLP-s4CQgDm',
  mapping: 'pathname',
  reactionsEnabled: '1',
  emitMetadata: '0',
  inputPosition: 'top',
  loading: 'lazy',
  lang: 'en',
};

/** Navigation bar 
 * Could this be automated?
*/
export const navConfig: (DD.Nav | DD.Link)[] = [
  {
    name: 'Get Started',
    orientation: 2,
    links: [
      {
        name: 'Hello World',
        url: '/hello-world',
        prefetch: true,
      },
      {
        name: 'Example Post',
        url: '/example',
        prefetch: true,
      },
      {
        name: 'Intro to QWER',
        url: '/intro-to-QWER',
        prefetch: true,
      },
    ],
  },
  {
    name: 'About',
    url: '/about',
  },
  {
    name: 'Get QWER 🚀',
    url: 'https://github.com/kwchang0831/svelte-QWER',
    target: '_blank',
    rel: 'noreferrer noopener',
  },
];

/** Navigation bar for mobile
 * Has this to be separated?
*/
export const mobilenavConfig: DD.Nav = {
  orientation: 2,
  links: [
    {
      name: 'Get Started',
      orientation: 1,
      links: [
        {
          name: 'Hello World',
          url: '/hello-world',
          prefetch: true,
        },
        {
          name: 'Example Post',
          url: '/example',
          prefetch: true,
        },
        {
          name: 'Intro to QWER',
          url: '/intro-to-QWER',
          prefetch: true,
        },
      ],
    },
    {
      name: 'About',
      url: '/about',
    },
    {
      name: 'Get QWER 🚀',
      url: 'https://github.com/kwchang0831/svelte-QWER',
      target: '_blank',
      rel: 'noreferrer noopener',
    },
  ],
};
