<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h2 id="qwer"><a href="#qwer">🎉 QWER</a></h2>
    <p>
      <a href="https://github.com/kwchang0831/svelte-QWER">QWER</a>
      is inspired by
      <a href="https://github.com/importantimport/urara">Urara</a>
      , but
      <a href="https://github.com/kwchang0831/svelte-QWER">QWER</a>
      &#39;s internal core was built differently. You can still check my previous blog:
      <a href="https://urara.kwchang0831.dev/">urara.kwchang0831.dev</a>
      that was built by
      <a href="https://github.com/importantimport/urara">Urara</a>
      .
    </p>
    <p>
      It took me about a month or two of my leisure time to develope <a
        href="https://github.com/kwchang0831/svelte-QWER">
        QWER
      </a>
      . It is also my first
      <a href="https://svelte.dev/">Svelte</a>
      +
      <a href="https://kit.svelte.dev/">SvelteKit</a>
       project. I just learned Svelte while developing it.
    </p>
    <ImgZoom src="/preview.png" alt="QWER Preview" />

    <ImgZoom src="/mobile-preview.png" alt="QWER Mobile Preview" />

    <h2 id="features"><a href="#features">✨ Features</a></h2>
    <ul>
      <li>
        <p>
          Writing post with <a href="https://www.markdownguide.org/basic-syntax/">Markdown syntax</a>
          .
        </p>
      </li>
      <li>
        <p>
          Outstanding site performance. Near perfect <a href="https://pagespeed.web.dev/">PageSpeed</a>
           score.
        </p>
      </li>
      <li><p>Mobile-First / Responsive design.</p></li>
      <li>
        <p>
          SEO friendly through meta, <a href="https://ogp.me/">Open Graph</a>
          ,
          <a href="https://schema.org/">Schema</a>
          ,
          <a href="https://json-ld.org/">JSON-LD</a>
          ,
          <a href="https://indieweb.org/microformats2">microformats2</a>
          .
        </p>
      </li>
      <li><p>Folder-based organization for creating posts.</p></li>
      <li><p>Post with tags and tag filtering feature.</p></li>
      <li><p>Post with auto generated table of content.</p></li>
      <li>
        <p>
          Out-of-the-box support for <a href="https://validator.w3.org/feed/docs/atom.html">Atom feed</a>
          , Sitemap,
          <a href="https://web.dev/progressive-web-apps/">PWA</a>
          .
        </p>
      </li>
      <li>
        <p>
          Automatic image optimization via <a href="https://github.com/JonasKruckenberg/imagetools">vite-imagetools</a>
          .
        </p>
      </li>
      <li><p>Support embedding Svelte components and Javascript with Markdown.</p></li>
      <li>
        <p>
          Supports <a href="https://github.com/giscus/giscus">Giscus</a>
           - a comments system powerd by Github Discussions.
        </p>
      </li>
      <li>
        <p>
          Utilizes <a href="https://github.com/unocss/unocss">UnoCSS</a>
           - the instant on-demand atomic CSS engine.
        </p>
      </li>
    </ul>
    <h2 id="current-state"><a href="#current-state">🚧 Current State</a></h2>
    <p>
      <a href="https://github.com/kwchang0831/svelte-QWER">QWER</a>
       is currently at pre-alpha stage. I used just-make-it-to-work approach, so a lot of places in the code are NOT optimized
      at all, ugly as hell. You have been warned. 😉
    </p>
    <p>
      If you have encountered any issues, please do let me know using <a
        href="https://github.com/kwchang0831/svelte-QWER/discussions/categories/q-a">
        Github&#39;s Q&amp;A Discussion board
      </a>
      .
    </p>
    <h2 id="end"><a href="#end">👍 END</a></h2>
    <p>
      Thanks so much for interesting in <a href="https://github.com/kwchang0831/svelte-QWER">QWER</a>
      . Please try it out and let me know what you think 😊.
    </p>
  </article>
</Post>
